--- #YAML:1.0
name:                Statistics-SocialNetworks
version:             0.03
abstract:            Perl extension for calculating network constraint and other network statistics.
license:             ~
author:              
    - Erich Morisse <esm@morisse.com>
generated_by:        ExtUtils::MakeMaker version 6.44
distribution_type:   module
requires:     
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
